#
# QuikR Travis buildscript.
#

# Tell Travis this is an R project.
language: r

# Tell Travis not to freak out about R compile warnings.
warnings_are_errors: false

# Tell Travis to cache packages, to save time.
cache: packages

# Tell Travis we don't need sudo.
sudo: false

# Tell Travis to use the trusty distribution.
dist: trusty

# Tell Travis which version(s) of R to use.
r:
  - oldrel
  - release
  - devel

# Tell Travis about R packages.
r_packages:
  - devtools

# Tell Travis what to do after a success.
after_success:
    - Rscript -e 'covr::codecov()'
